name: Run MLQA-TSR Pipeline

on:
  workflow_dispatch:   # Cho phép chạy thủ công
    inputs:
      split:
        description: "Chọn tập dữ liệu để chạy"
        required: true
        default: "public_task1"
        type: choice
        options:
          - train
          - public_task1
          - public_task2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          echo "▶️ Bắt đầu chạy pipeline với split=${{ github.event.inputs.split }}"
          python scripts/predict.py --split ${{ github.event.inputs.split }}

      - name: Upload artifacts (submission)
        uses: actions/upload-artifact@v3
        with:
          name: submission-${{ github.event.inputs.split }}
          path: |
            submission_${{ github.event.inputs.split }}.json
            submission.zip
